services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: $${POSTGRES_USER}
      POSTGRES_PASSWORD: $${POSTGRES_PASSWORD}
      POSTGRES_DB: $${POSTGRES_DB}
    env_file:
      - .env.dev 
    volumes:
      - postgres_airflow:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  airflow-init:
    image: apache/airflow:2.9.0
    entrypoint: /bin/bash -c "airflow db migrate && airflow users create --username admin --firstname admin --lastname User --role Admin --email admin@example.com --password admin"
    env_file:
      - .env.dev
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres

  webserver:
    image: apache/airflow:2.9.0
    env_file:
      - .env.dev
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver
    depends_on:
      - airflow-init

  scheduler:
    image: apache/airflow:2.9.0
    env_file:
      - .env.dev
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    depends_on:
      - webserver

  worker:
    image: apache/airflow:2.9.0
    env_file:
      - .env.dev
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: celery worker
    depends_on:
      - scheduler

volumes:
  postgres_airflow: